### ISSUE TITLE
XPath functionality does not show up in Command Palette

### ISSUE THREAD

**Issue by Rufus125** [rosshadden/sublime-xpath#41]
No xquery functionality is shown, only "Set Syntax: XPath 1.0"

Another user had the same issue: https://stackoverflow.com/questions/45586508/sublime-text-xpath-plugin-shortcut#comment78418021_45679384

Sublime Version 3.2 on Windows 10

**Comment by keith-hall** [comment]
Hi, thanks for reporting and sorry to hear you are having trouble.
I have some questions to help us diagnose where the problem lies, apologies if they are very basic but it verifies we are on the same page:

- are you in an XML file or a HTML file which is valid XML?
- are there any errors in the ST console? (View menu -> Show Console)
- how about messages in the status bar?
- does uninstalling the XPath package and reinstalling help? (or does Package Control show any errors installing the `lxml` dependency perhaps?)
- does typing `from lxml import etree` <kbd>Enter</kbd> in the ST console cause any errors to be shown?

**Comment by Rufus125** [comment]
Hi Keith!

Thanks for your answer!
The solution was your first question. I did not have a valix XML file open and therefore the commands did not appear!

**Comment by keith-hall** [comment]
yay, glad we got it sorted, thanks for replying. Maybe it could be useful to add some commands to the command palette for other files, which when used, could show a message about why the main functionalities are unavailable. What do you think, would it be more user friendly? :) I think it could help others in the same situation :)
