### ISSUE TITLE
Noticed recent change in how xpath is generated.

### ISSUE THREAD

**Issue by rcranney** [rosshadden/sublime-xpath#5]
First off, I really like this package, it has been a life saver...

Until recently, when I used XPATH, it would paste the XPATH as
/ForecastCanonical/FCST_INFO

Now it pastes the XPATH as
/ForecastCanonical[1]/FCST_INFO[1]

I presume that in some cases this would be helpful, but generally is not with the XML files I work with.  can the old functionality be restored by setting something in user Settings?

**Comment by keith-hall** [comment]
You're right, it is a change I made recently so blame me ;)

good idea, I will add a setting for it :)

**Comment by rosshadden** [comment]
Oh sorry, I didn't even think of that when merging in Keith's stuff.  I agree that it should be an option, however I'm not sure what we should make the default.  I think not having the indices is more universally useful, however it as not really true "xpath".

I'm leaning toward us making them two separate commands, rather than one command with options.  I can see it being useful to use both of the commands and it would therefore not make sense to have it depend on user configuration.

**Comment by rcranney** [comment]
Having both as an option on a right click menu is fine by me, if that was what you were suggesting.

**Comment by keith-hall** [comment]
I have made a fix for this, but something to be aware of is that my changes remove the entry from the context menu, and therefore the command to copy the xpath and the command to copy the hierarchy to the clipboard will only be available from the Command Pallette by default.

My reason for removing it was because I felt that some plugins add too many items to the context menu and it gets too crowded.  Especially as I have added a few extra navigation commands to the plugin, I didn't want them all in the context menu.
It is easy for users to edit their own context menu and customize exactly what they want to see there, although official documentation on it doesn't seem too great from a quick search that I just did... so feel free to re-create the Context.sublime-menu file if you want @rosshadden

Apologies for any inconvenience I have caused with my changes!

**Comment by rosshadden** [comment]
@keith-hall Would you mind making a pull request for your added features?  That's the easiest way to approach this.  I will add the context menu file back in.

I don't disagree with your reasoning for removing it---however at this point `sublime-xpath` is a reasonably well-established plugin, and I don't want to remove functionality that has been there from the beginning.  When I used Sublime I guess I didn't have many plugins that added to the context menu, so for me it seemed like a very convenient place.

**Comment by keith-hall** [comment]
Pull request created :+1: 

I agree, we shouldn't remove existing functionality and thus confuse or annoy our users, I guess I need to get used to seeing the bigger picture when I decide I want to change something for myself :)

**Comment by rosshadden** [comment]
No, not at all.  What you did is the embodiment of open source.  In all honesty, I feel honored that you like this project enough to change it to fit your needs even more.
